// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using werehouse_api.Data;

#nullable disable

namespace werehouse_api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402015152_KioskAndPinCodeDataAdded")]
    partial class KioskAndPinCodeDataAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("werehouse_api.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PinCode")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "MK"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Maintenance"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Custodial"
                        });
                });

            modelBuilder.Entity("werehouse_api.Entities.InventoryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("LastRestocked")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "A1-01D-01",
                            Name = "Disposable Coverall Medium /Each",
                            SKU = "48678",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 2,
                            Location = "A1-01D-02",
                            Name = "Disposable Coverall Large /Each",
                            SKU = "48679",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 3,
                            Location = "A1-01D-03",
                            Name = "Disposable Coverall XL /Each",
                            SKU = "48680",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 4,
                            Location = "A1-01D-04A",
                            Name = "Vacuum Bag, For Super Coach Pro 6, GoFree Pro, and ProVac FS6 /Each Pack of 10",
                            SKU = "CS485",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 5,
                            Location = "A1-01D-04B",
                            Name = "Vacuum Bag For Hip Hugger /Each Pack of 10",
                            SKU = "CS420",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 6,
                            Location = "A1-01C-01",
                            Name = "Vacuum Bags Lavex /Each Pack of 9",
                            SKU = "64789",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 7,
                            Location = "A1-01C-02",
                            Name = "Vacuum Bag For Versamatic VS14 /Each Pack of 10",
                            SKU = "CS425",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 8,
                            Location = "A1-01C-02B",
                            Name = "Vacuum Bag Sanitaire SC9180, S9100, and C4900 /Each Pack of 5",
                            SKU = "38784",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 9,
                            Location = "A1-01C-03",
                            Name = "Vacuum Bag, Windsor For Versamatic VSP14 /Each Pack of 10",
                            SKU = "CS430",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 10,
                            Location = "A1-01C-04",
                            Name = "Vacuum Bag, ST Sanitaire/ 5/Pack",
                            SKU = "62713",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 11,
                            Location = "A1-01C-05",
                            Name = "Vacuum Bag Lavex 12\" upright/ 9/Pack",
                            SKU = "63393",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 12,
                            Location = "A1-01C-06",
                            Name = "Vacuum Bag Style LS/ 9/Pack",
                            SKU = "64650",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 13,
                            Location = "A1-01B-01",
                            Name = "Trash Bags Clear, 43\" x 48\" (200/Box",
                            SKU = "PP435",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 14,
                            Location = "A1-01B-02",
                            Name = "Trash Bags Clear, 24\" x 24\" (1000/Box",
                            SKU = "PP415",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 15,
                            Location = "A1-01B-03",
                            Name = "Trash Bags Clear, 33\" x 39\" (250/Box",
                            SKU = "PP425",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 16,
                            Location = "A1-01A-01",
                            Name = "Trash Bags Black, 44\" x 55\" (100/Box",
                            SKU = "PP450",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 17,
                            Location = "A1-01A-02",
                            Name = "Trash Bags Black, 43\" x 47\" (100/Box",
                            SKU = "PP455",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 18,
                            Location = "A1-02C-01",
                            Name = "Trash Bags, Sanitary Napkin Liners, 12\" x 6\" (500/Box",
                            SKU = "FP120",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 19,
                            Location = "A1-02C-02",
                            Name = "Deli Paper 10\" x 10.75\" (500/Box",
                            SKU = "PP335",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 20,
                            Location = "A1-02C-03",
                            Name = "Tampon Procter and Gamble (Each",
                            SKU = "FP105",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 21,
                            Location = "A1-02C-04",
                            Name = "Maxi Pad Gards, Hospitality Specialty Co. (Each",
                            SKU = "FP115",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 22,
                            Location = "A1-02B-01",
                            Name = "Trash Bags Black, 49\" x 53\" (75/Box",
                            SKU = "PP460",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 23,
                            Location = "A1-02B-02",
                            Name = "Trash Bags Black 58\" x 38\" (100 Box",
                            SKU = "60707",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 24,
                            Location = "A1-02A-01",
                            Name = "Trash Bags Clear, 27\" x 35\" (500/Box",
                            SKU = "PP400",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 25,
                            Location = "A1-02A-02",
                            Name = "Trash Bags Clear, 24\" x 33\" (1000/Box",
                            SKU = "PP420",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 26,
                            Location = "A1-03C-01",
                            Name = "8 oz Disposable Beverage Cups For Hot or Cold Drinks (Each Box",
                            SKU = "49618",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 27,
                            Location = "A1-03C-02",
                            Name = "5 oz Disposable Beverage Cups For Cold Drinks Each Box 5 0z Disposable Beverage Cups For Cold Drinks (Each Box",
                            SKU = "PP205",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 28,
                            Location = "A1-03C-03",
                            Name = "9 oz Disposable Beverage Cups For Cold Drinks (Each Box",
                            SKU = "PP211",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 29,
                            Location = "A1-03C-04",
                            Name = "Facial Tissue, Victoria Bay Rectangular Box (Each Tissue Box",
                            SKU = "PP131",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 30,
                            Location = "A1-03B-01",
                            Name = "Baby Wipe Huggies, Unscented Tubs",
                            SKU = "63747",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 31,
                            Location = "A1-03B-02",
                            Name = "Facial Tissue, Kleenex Cardboard Cube (Each",
                            SKU = "PP101",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 32,
                            Location = "A1-03B-03",
                            Name = "Napkin, Luncheon White Paper 12PK/CS Napkin, Luncheon White Paper 12PK/CS Napkin, Luncheon White Paper 12PK/CS",
                            SKU = "PP328",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 33,
                            Location = "A1-03A-01",
                            Name = "WypAll, All-Purpose Wipes, White (Each Pack",
                            SKU = "PP320",
                            Stock = 10,
                            Unit = "Unit"
                        },
                        new
                        {
                            Id = 34,
                            Location = "A1-03A-02",
                            Name = "WypAll, Wipes Kimberly-Clark (Each Box",
                            SKU = "PP315",
                            Stock = 10,
                            Unit = "Unit"
                        });
                });

            modelBuilder.Entity("werehouse_api.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedUserUsername")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PickedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceivedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReceivedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestedUserUsername")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedUserUsername");

                    b.HasIndex("RequestedUserUsername");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("werehouse_api.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("InventoryItemId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("werehouse_api.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Supervisor"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Staff"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Dept Head"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Tool Cage Operator"
                        });
                });

            modelBuilder.Entity("werehouse_api.Entities.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CheckedOutAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentHolderUsername")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DueAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExpectedDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsKioskCheckout")
                        .HasColumnType("bit");

                    b.Property<string>("KioskId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KioskName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LocationOfUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerUsername")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ToolCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentHolderUsername");

                    b.HasIndex("OwnerUsername");

                    b.HasIndex("ToolCategoryId");

                    b.ToTable("Tools");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Impact Drill (DeWalt)",
                            Status = "available",
                            ToolCategoryId = 2
                        },
                        new
                        {
                            Id = 2,
                            Name = "Angle Grinder",
                            Status = "available",
                            ToolCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ladder 6ft",
                            Status = "available",
                            ToolCategoryId = 4
                        },
                        new
                        {
                            Id = 4,
                            Name = "Safety Harness",
                            Status = "available",
                            ToolCategoryId = 3
                        });
                });

            modelBuilder.Entity("werehouse_api.Entities.ToolCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ToolCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Hand Tools"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Power Tools"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Safety"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Ladders"
                        });
                });

            modelBuilder.Entity("werehouse_api.Entities.ToolHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime2");

                    b.Property<string>("BorrowerUserUsername")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ByUserUsername")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool?>("Clean")
                        .HasColumnType("bit");

                    b.Property<string>("ExpectedDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsKioskCheckout")
                        .HasColumnType("bit");

                    b.Property<string>("KioskId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("KioskName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LocationOfUse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StaffUserUsername")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ToolId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BorrowerUserUsername");

                    b.HasIndex("ByUserUsername");

                    b.HasIndex("StaffUserUsername");

                    b.HasIndex("ToolId");

                    b.ToTable("ToolHistories");
                });

            modelBuilder.Entity("werehouse_api.Entities.User", b =>
                {
                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Username");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("werehouse_api.Entities.Order", b =>
                {
                    b.HasOne("werehouse_api.Entities.User", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedUserUsername");

                    b.HasOne("werehouse_api.Entities.User", "RequestedUser")
                        .WithMany()
                        .HasForeignKey("RequestedUserUsername");

                    b.Navigation("AssignedUser");

                    b.Navigation("RequestedUser");
                });

            modelBuilder.Entity("werehouse_api.Entities.OrderItem", b =>
                {
                    b.HasOne("werehouse_api.Entities.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("werehouse_api.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("werehouse_api.Entities.Tool", b =>
                {
                    b.HasOne("werehouse_api.Entities.User", "CurrentHolder")
                        .WithMany()
                        .HasForeignKey("CurrentHolderUsername");

                    b.HasOne("werehouse_api.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerUsername");

                    b.HasOne("werehouse_api.Entities.ToolCategory", "ToolCategory")
                        .WithMany()
                        .HasForeignKey("ToolCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentHolder");

                    b.Navigation("Owner");

                    b.Navigation("ToolCategory");
                });

            modelBuilder.Entity("werehouse_api.Entities.ToolHistory", b =>
                {
                    b.HasOne("werehouse_api.Entities.User", "BorrowerUser")
                        .WithMany()
                        .HasForeignKey("BorrowerUserUsername");

                    b.HasOne("werehouse_api.Entities.User", "ByUser")
                        .WithMany()
                        .HasForeignKey("ByUserUsername");

                    b.HasOne("werehouse_api.Entities.User", "StaffUser")
                        .WithMany()
                        .HasForeignKey("StaffUserUsername");

                    b.HasOne("werehouse_api.Entities.Tool", "Tool")
                        .WithMany("ToolHistories")
                        .HasForeignKey("ToolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BorrowerUser");

                    b.Navigation("ByUser");

                    b.Navigation("StaffUser");

                    b.Navigation("Tool");
                });

            modelBuilder.Entity("werehouse_api.Entities.User", b =>
                {
                    b.HasOne("werehouse_api.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.HasOne("werehouse_api.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("werehouse_api.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("werehouse_api.Entities.Tool", b =>
                {
                    b.Navigation("ToolHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
